import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppinsfont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppinsfont.className} h-full antialiased`}
    >
      <body>
        <Navbar />
        
        <main className="w-full min-h-screen">{children}</main>
      </body>
    </html>
  );
}